
name: intima_app
description: "Application de santé sexuelle et reproductive pour femmes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^14.0.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Base de données locale
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Sécurité
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
  # HTTP & API
  dio: ^5.4.0
  
  # UI & Animations
  smooth_page_indicator: ^1.1.0
  
  # Utilitaires
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/